### ISSUE TITLE
Problem with libxmljs dependency

### ISSUE THREAD

**Issue by antonsavchenko94** [taskcluster/fast-azure-storage#25]
I'm faced with problem to deploy Node.js app to Azure. I use fast-azure-storage for uploading files to azure blob storage. Locally every things work perfect, but when I  trying to deploy it to Azure I have got error:

`
> libxmljs@0.18.7 install D:\local\Temp\8d4ca9654babd57\bundle\programs\server\npm\node_modules\libxmljs
debug:   > node-pre-gyp install --fallback-to-build --loglevel http
debug:    
debug:   'node-pre-gyp' is not recognized as an internal or external command,
debug:   operable program or batch file.
debug:   npm ERR! code ELIFECYCLE
debug:   npm ERR! errno 1
debug:   npm ERR! libxmljs@0.18.7 install: `node-pre-gyp install --fallback-to-build --loglevel http`
debug:   npm ERR! Exit status 1
debug:   npm ERR! 
debug:   npm ERR! Failed at the libxmljs@0.18.7 install script.
debug:   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
debug:    
debug:   npm ERR! A complete log of this run can be found in:
debug:   npm ERR!     D:\local\AppData\npm-cache\_logs\2017-07-14T08_59_56_308Z-debug.log
`

I read Azure documentation, and found -  'Azure App Service does not support all native modules and might fail at compiling those with very specific prerequisites."
Can You fix that ? Or give tips on how to use your package with Azure deploy.

Thanks!

**Comment by jonasfj** [comment]
libxmljs is an optional dependency: https://github.com/taskcluster/fast-azure-storage/blob/4e74210fcf452c62b7319cdaa392a2d69c4ac154/package.json#L25-L27
Probably you need to lock dependencies and ensure that libxmljs isn't part of your lock file. I assume you mean "Azure Websites" by "Azure deploy".. I have no idea how it works, or if it does the right thing.

If libxmljs isn't installed fast-azure-storage will fallback to use pixl-xml, which is also reasonably fast.

---
On a personal note, I wouldn't recommend using Windows for anything ever, most certainly not running servers, that's just asking for trouble :)
